export const CONSTANTS = {
  taskListTitle: "Task List",
  noTasksMessage: "Currently you don't have any task!!",
  enterTitlePlaceholder: "Enter Title",
  titleLabel: "Title",
  enterDescriptionPlaceholder: "Enter Description",
  descriptionLabel: "Description",
  addTaskButton: "Add Task",
  titleRequiredError: "Title is required",
  descriptionRequiredError: "Description is required",
  descriptionMinLengthError: "Description must be at least 10 characters long",
  doneMessage: "Done",
  taskDetailsTitle: "Task Details",
  createdOnLabel: "Created on",
  updateTaskButtonLabel: "Update Task",
};
